[package]
name = "tlrc"
version = "1.7.0"
description = "A tldr client written in Rust"
categories = ["command-line-utilities"]
homepage = "https://github.com/tldr-pages/tlrc"
repository = "https://github.com/tldr-pages/tlrc"
documentation = "https://tldr.sh/tlrc"
license = "MIT"
edition = "2021"
rust-version = "1.70"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
dirs = "5.0.1"
ring = "0.17.5"
serde = { version = "1.0.190", features = ["derive"] }
toml = "0.8.6"
ureq = { version = "2.8.0", default-features = false, features = ["tls"] }
yansi = "0.5.1"
zip = { version = "0.6.6", default-features = false, features = ["deflate"] }

[build-dependencies]
clap = { version = "4.4.7", features = ["derive"] }
clap_complete = "4.4.4"

[dev-dependencies]
assert_cmd = "2.0.12"

[[bin]]
name = "tldr"
path = "src/main.rs"

[profile.release]
lto = true
strip = true
codegen-units = 1
panic = "abort"
