[package]
name = "tlrc"
version = "1.0.0"
description = "A tldr client written in Rust"
homepage = "https://github.com/acuteenvy/tlrc"
repository = "https://github.com/acuteenvy/tlrc"
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2", features = ["derive", "cargo"] }
ureq = "2.6"
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"
zip = { version = "0.6.4", features = ["deflate"], default-features = false }
yansi = "0.5"
is-terminal = "0.4"
dirs = "5"

[[bin]]
name = "tldr"
path = "src/main.rs"

[profile.release]
lto = true
strip = true
codegen-units = 1
panic = "abort"
